### ISSUE TITLE
Is the paper going to be released?

### ISSUE THREAD

**Issue by ding3820** [Alpha-VL/FastConvMAE#1]
Hi,
ConvMAE is an interesting work and this work seems to take it to the next level. I'm looking forward to seeing the official paper. May I know is there any plan to release the paper? Thanks!

**Comment by gaopengpjlab** [comment]
Thanks for your interest in ConvMAE. FastConvMAE will be released in the extended version of the original arxiv paper. The updated manuscript should be released within a few weeks. Stay tuned.
